# Generated by Django 4.0.4 on 2022-06-21 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Brand name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Brand slug')),
                ('description', models.TextField(blank=True, max_length=450, verbose_name='Brand descrition')),
                ('brand_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Brand user')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category slug')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True, verbose_name='Size')),
                ('size_type', models.CharField(blank=True, max_length=20, verbose_name='Size type')),
            ],
            options={
                'verbose_name': 'Sizes',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='inventory.sizes')),
            ],
            options={
                'verbose_name_plural': 'Product sizes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='Product sku')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Product slug')),
                ('description', models.TextField(blank=True, max_length=455, verbose_name='Product description')),
                ('color', models.CharField(blank=True, max_length=55)),
                ('image', models.ImageField(blank=True, upload_to='media/products/', verbose_name='product image')),
                ('image2', models.ImageField(blank=True, upload_to='media/products/', verbose_name='product image 2')),
                ('image3', models.ImageField(blank=True, upload_to='media/products/', verbose_name='product image 3')),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('made_by', models.CharField(max_length=255, verbose_name='Made by brand')),
                ('store_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('is_sale_price_active', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='inventory.brand')),
                ('category', models.ManyToManyField(blank=True, related_name='product_categories', to='inventory.category')),
                ('sizes', models.ManyToManyField(null=True, related_name='item_product_sizes', to='inventory.productsizes')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
