# Generated by Django 4.0.4 on 2023-02-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Brand name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Brand slug')),
                ('description', models.TextField(blank=True, max_length=450, verbose_name='Brand descrition')),
                ('brand_image', models.ImageField(blank=True, upload_to='media/brands/', verbose_name='brand image')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category slug')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=24, unique=True, verbose_name='Discount code')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Discount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name_plural': 'Discount codes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='Product sku')),
                ('slug', models.SlugField(max_length=255, verbose_name='Product slug')),
                ('description', models.TextField(blank=True, max_length=455, verbose_name='Product description')),
                ('color', models.CharField(blank=True, max_length=55)),
                ('image', models.ImageField(blank=True, upload_to='media/products/', verbose_name='product image')),
                ('image2', models.ImageField(blank=True, upload_to='media/products/', verbose_name='product image 2')),
                ('image3', models.ImageField(blank=True, upload_to='media/products/', verbose_name='product image 3')),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('made_by', models.CharField(max_length=255, verbose_name='Made by brand')),
                ('store_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('is_sale_price_active', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='inventory.brand')),
                ('category', models.ManyToManyField(blank=True, related_name='product_categories', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Product sizes',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, unique=True, verbose_name='Size')),
                ('size_type', models.CharField(blank=True, max_length=20, verbose_name='Size type')),
            ],
            options={
                'verbose_name': 'Sizes',
                'verbose_name_plural': 'Sizes',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SoldProductConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_number_code', models.SlugField(max_length=24, unique=True, verbose_name='Product number confirmation slug')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('discount', models.CharField(blank=True, max_length=20, verbose_name='discount')),
                ('confirmation', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.CharField(blank=True, default='', max_length=54)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_sold', to='inventory.product')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_size_sold', to='inventory.productsizes')),
                ('sold_confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_product_confirmation', to='inventory.soldproductconfirmation')),
            ],
        ),
        migrations.AddField(
            model_name='productsizes',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='inventory.sizes'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='item_product_sizes', to='inventory.productsizes'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_filter_categories',
            field=models.ManyToManyField(blank=True, related_name='brand_categories', to='inventory.category'),
        ),
    ]
