# Generated by Django 4.0.4 on 2023-02-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
