# Generated by Django 4.0.4 on 2022-08-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.SlugField(max_length=24, unique=True, verbose_name='Discount code'),
        ),
    ]
