# Generated by Django 4.0.4 on 2023-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_soldproduct_product_soldproduct_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, default='media/brands/default.jpg', upload_to='media/brands/', verbose_name='brand image'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='size',
            field=models.CharField(blank=True, max_length=54),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
