# Generated by Django 4.0.4 on 2022-08-30 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_mail', to='inventory.product')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_size_mail', to='inventory.productsizes')),
            ],
        ),
        migrations.CreateModel(
            name='SoldProductConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_number_slug', models.SlugField(max_length=24, unique=True, verbose_name='Product number confirmation slug')),
                ('confirmation', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.soldproduct', verbose_name='sold_product_confirmation')),
            ],
        ),
    ]
