# Generated by Django 4.0.4 on 2022-08-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_sold_number_slug_soldproductconfirmation_sold_number_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproductconfirmation',
            name='sold_products',
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='sold_confirmation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold_product_confirmation', to='inventory.soldproductconfirmation'),
            preserve_default=False,
        ),
    ]
