# Generated by Django 4.0.4 on 2022-08-31 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_soldproductconfirmation_sold_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='sold_confirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_product_confirmation', to='inventory.soldproductconfirmation'),
        ),
    ]
