# Generated by Django 4.0.4 on 2022-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_soldproduct_name_alter_soldproduct_sold_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
