# Generated by Django 4.0.4 on 2022-09-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_soldproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='size',
            field=models.CharField(blank=True, default='', max_length=54),
        ),
    ]
