# Generated by Django 4.0.4 on 2022-09-16 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_sold', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_size_sold', to='inventory.productsizes'),
        ),
    ]
