# Generated by Django 4.0.4 on 2023-01-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_soldproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizes',
            options={'ordering': ['pk'], 'verbose_name': 'Sizes', 'verbose_name_plural': 'Sizes'},
        ),
    ]
