# Generated by Django 4.0.4 on 2023-02-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_brand_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Brands'},
        ),
    ]
